(() => {
  const ns='http://www.w3.org/2000/svg';
  const paths={spark:'m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6Z',check:'m5 12 4 4L19 6',close:'m6 6 12 12M18 6 6 18',settings:'M4 7h16M4 17h16M9 4v6M15 14v6',undo:'M8 4 3 9l5 5M3 9h10a7 7 0 0 1 7 7v3',book:'M12 6v15M3 3h5a4 4 0 0 1 4 3 4 4 0 0 1 4-3h5v15h-5a4 4 0 0 0-4 3 4 4 0 0 0-4-3H3Z',arrow:'m9 5 7 7-7 7',pause:'M8 5v14M16 5v14'};
  function icon(name){const svg=document.createElementNS(ns,'svg');for(const [k,v]of Object.entries({viewBox:'0 0 24 24',fill:'none',stroke:'currentColor','stroke-width':'1.8','stroke-linecap':'round','stroke-linejoin':'round','aria-hidden':'true'}))svg.setAttribute(k,v);const p=document.createElementNS(ns,'path');p.setAttribute('d',paths[name]||paths.spark);svg.append(p);return svg;}
  function node(tag,attrs={},children=[]){const n=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(k==='text')n.textContent=v;else if(k==='class')n.className=v;else n.setAttribute(k,v);}for(const c of children)n.append(c);return n;}
  function create(){
    const host=node('div',{'data-escrita-root':'2','data-escrita-ignore':''}),root=host.attachShadow({mode:'open'});
    const css=node('style',{text:`
      :host{all:initial;position:fixed!important;inset:0!important;z-index:2147483647!important;pointer-events:none!important;color-scheme:light dark}*{box-sizing:border-box}button,select{font:inherit}button{cursor:pointer}button:disabled{cursor:default;opacity:.5}svg{width:18px;height:18px;flex-shrink:0}button:focus-visible,select:focus-visible{outline:3px solid #a99aff;outline-offset:3px}[hidden]{display:none!important}
      .ui{--bg:#fff;--fg:#20203f;--muted:#686880;--line:#e4e2f2;--soft:#f5f3ff;--accent:#6246e5;font:13px/1.5 system-ui,sans-serif;color:var(--fg)}.ui.dark{--bg:#1d1d31;--fg:#f5f3ff;--muted:#b6b0d0;--line:#3e3b57;--soft:#2b2843;--accent:#aa96ff}
      .badge{position:absolute;pointer-events:auto;display:flex;align-items:center;gap:7px;border:1px solid #8f76ff;border-radius:30px;padding:7px 12px;color:#fff;background:linear-gradient(120deg,#3459e8,#803bd9);box-shadow:0 4px 15px #4434aa35;font-size:12px;white-space:nowrap}.badge svg{width:17px}.badge .count{background:#fff2;border-radius:12px;padding:0 6px}
      .panel{position:absolute;pointer-events:auto;width:348px;max-width:calc(100vw - 16px);max-height:calc(100vh - 24px);overflow:auto;border:1px solid var(--line);border-radius:18px;background:var(--bg);box-shadow:0 16px 55px #15103d38}.head{background:linear-gradient(120deg,#3459e8,#803bd9);color:white;padding:16px;display:flex;align-items:center;gap:9px}.brand{font-weight:750;font-size:17px;flex:1}.head button{background:#ffffff20;color:white;border:0;border-radius:7px;padding:4px;display:flex}.body{padding:16px}.status{font-size:12px;color:var(--muted);margin-bottom:12px}.metrics{font-size:11px;color:var(--muted);margin-top:12px}.toolbar{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin:10px 0}.button{display:inline-flex;align-items:center;justify-content:center;gap:6px;border:1px solid var(--line);background:var(--soft);color:var(--fg);border-radius:9px;padding:8px 10px;font-weight:600}.primary{background:linear-gradient(120deg,#3459e8,#803bd9);color:white;border:0}.issue{width:100%;text-align:left;display:block;border:1px solid var(--line);border-left:3px solid var(--color);border-radius:9px;background:var(--bg);color:var(--fg);padding:10px;margin:7px 0}.category{font-size:10px;letter-spacing:.5px;text-transform:uppercase;color:var(--color);font-weight:750}.quote{white-space:pre-wrap;overflow-wrap:anywhere;font-weight:600;margin:5px 0}.detail{border-top:1px solid var(--line);padding-top:12px;margin-top:10px}.explain{color:var(--muted);margin:7px 0 12px}.replacement{display:block;width:100%;text-align:left;margin:6px 0;white-space:pre-wrap;overflow-wrap:anywhere}.list{max-height:235px;overflow:auto}label{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:12px}input{accent-color:#7151e8}select{padding:8px;border:1px solid var(--line);border-radius:9px;color:var(--fg);background:var(--soft);max-width:100%}.selection{padding:10px;background:var(--soft);border-radius:10px;margin:10px 0;max-height:100px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}.mark{position:absolute;pointer-events:auto;border:0;border-bottom:3px solid var(--color);padding:0;background:transparent;border-radius:1px;height:5px}.mark:hover,.mark:focus-visible{background:var(--color);opacity:.65}.empty{padding:15px 0;color:var(--muted)}
    `});
    const ui=node('div',{class:'ui'}),marks=node('div'),badge=node('button',{class:'badge','aria-label':'Abrir revisão Escrita IA','aria-expanded':'false'},[icon('spark')]),badgeText=node('span',{text:'Escrita IA'}),count=node('span',{class:'count',text:'0'}),badgeMetrics=node('span');badge.append(badgeText,count,badgeMetrics);
    const panel=node('section',{class:'panel',role:'dialog','aria-label':'Revisão de escrita'}),head=node('div',{class:'head'}),close=node('button',{'aria-label':'Fechar revisão'},[icon('close')]);head.append(icon('spark'),node('span',{class:'brand',text:'Escrita IA'}),close);
    const body=node('div',{class:'body'}),status=node('div',{class:'status',role:'status','aria-live':'polite'}),tools=node('div',{class:'toolbar'}),settings=node('button',{class:'button','aria-label':'Configurações'},[icon('settings')]),retry=node('button',{class:'button',text:'Revisar'}),undo=node('button',{class:'button',text:'Desfazer'}),list=node('div',{class:'list'}),detail=node('div',{class:'detail'}),rewrite=node('div'),metrics=node('div',{class:'metrics'});
    tools.append(retry,undo,settings);body.append(status,list,detail,rewrite,tools,metrics);panel.append(head,body);ui.append(marks,badge,panel);root.append(css,ui);document.documentElement.append(host);panel.hidden=true;badge.hidden=true;undo.hidden=true;detail.hidden=true;
    const colors={spelling:'#e04466',grammar:'#b57904',punctuation:'#b57904',typography:'#b57904',style:'#8953ed',tone:'#8953ed'};
    return {host,root,ui,marks,badge,badgeText,count,badgeMetrics,panel,body,status,settings,retry,undo,list,detail,rewrite,metrics,close,node,icon,colors};
  }
  globalThis.EscritaPanel={create};
})();
